### ISSUE TITLE
Question about End2End.py

### ISSUE THREAD

**Issue by smiura-ai** [vicoslab/mixed-segdec-net-comind2021#10]
Thank you so much for sharing the scripts.

In line 129 of "End2End.py", "training_iteration()" returns "total_loss_seg + total_loss_dec" instead of "total_loss".
Is it supposed to mean something?

**Comment by JakobBozic** [comment]
Hi, 
it doesn't mean anything, just a minor bug. I have updated the code to return the total_loss, thank you for bringing this to our attention.
