### ISSUE TITLE
Run KSDD/download_and_extract.py

### ISSUE THREAD

**Issue by miwaliu** [vicoslab/mixed-segdec-net-comind2021#2]
Where can we download this file download_and_extract.py

**Comment by skokec** [comment]
Hi, I have added the missing files to the [datasets/KSDD](https://github.com/vicoslab/mixed-segdec-net-comind2021/tree/master/datasets/KSDD) and [datasets/KSDD2](https://github.com/vicoslab/mixed-segdec-net-comind2021/tree/master/datasets/KSDD2) folders.

**Comment by miwaliu** [comment]
TKS
