### ISSUE TITLE
generate models by training on STEEL data

### ISSUE THREAD

**Issue by rashi-b** [vicoslab/mixed-segdec-net-comind2021#21]
Hi , 
can you please tell me as to what parameters to use to train the model to get the AP 99.99% (as mentioned in paper)? I tried to train using below parameters on STEEL dataset but achieved AP 75% only. Also could you please tell me how is the class information given to the model for this dataset?
```
python -u train_net.py  \
        --GPU=0 \
        --DATASET=STEEL \
        --RUN_NAME=steel_server_1 \
        --DATASET_PATH=datasets/STEEL \
        --RESULTS_PATH=datasets/steel_result_1 \
        --SAVE_IMAGES=True \
        --DILATE=7 \
        --EPOCHS=50 \
        --VALIDATION_N_EPOCHS=5 \
        --LEARNING_RATE=0.1 \
        --DELTA_CLS_LOSS=0.1 \
        --BATCH_SIZE=500 \
        --WEIGHTED_SEG_LOSS=True \
        --WEIGHTED_SEG_LOSS_P=2 \
        --WEIGHTED_SEG_LOSS_MAX=1 \
        --DYN_BALANCED_LOSS=True \
        --GRADIENT_ADJUSTMENT=True \
        --FREQUENCY_SAMPLING=True \
        --TRAIN_NUM=3000 \
        --NUM_SEGMENTED=3000 \
        --FOLD=0
```

Thanks

**Comment by JakobBozic** [comment]
Hi, 
parameters can be found in EXPERIMENTS_COMIND.sh. Best results (99.3% AP ) are achieved when all 3000 samples are fully labeled, this can be seen in line 62 in EXPERIMENTS_COMIND.sh.

There is no class information for any of the datasets, we only used one class of defects from the Severstal steel datasest, more details are in the paper.

Kind regards, Jakob
