### ISSUE TITLE
torch.jit.trace error

### ISSUE THREAD

**Issue by jjqcat** [vicoslab/mixed-segdec-net-comind2021#27]
Thanks for your great project, and I need to use jit.trace convert model to libtorch(C++) model ,code as below

model.to(device)
model.cuda()
model.eval()
example = torch.rand(1, 3, INPUT_HEIGHT,INPUT_WIDTH).cuda() 
traced_script_module = torch.jit.trace(model, example)
traced_script_module.save("model_for_libtorch.pt")

RuntimeError: 
Could not export Python function call 'GradientMultiplyLayer'. Remove calls to Python functions before export. Did you forget to add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:

**Comment by jjqcat** [comment]
torch 1.11+cu113

**Comment by JakobBozic** [comment]
GradientMultiplyLayer is only used during the training, you could make another SegDec model class without it and then use the original for training, export the weights and load them to an instance of a new class for inference and/or exporting to libtorch.

**Comment by jjqcat** [comment]
I see, but the new model's forward method ,which use volume_lr_multiplier_layer ,glob_max_lr_multiplier_layer and so on, how to modify these codes？ Thanks

**Comment by JakobBozic** [comment]
You can remove all calls to any of these three layers in the new class as they do nothing during the forward pass.

**Comment by jjqcat** [comment]
OK, I see ,Thanks
