### ISSUE TITLE
KSDD2 splits Question

### ISSUE THREAD

**Issue by smiler96** [vicoslab/mixed-segdec-net-comind2021#4]
hello, the number of the positive data is 246, all same in five different splits, is there anything wrong?
I think that the number in the name of the split represents the number of the positive data, do i make something wrong?

**Comment by JakobBozic** [comment]
Hi,
the number in the name of the split for KSDD2 represents the number of fully labeled samples (N in the paper).
The number of positive training samples for KSDD2 is always 246 for all experiments.
I have updated all README.md files in the splits directory with better explanations of the numbers in the names.

**Comment by smiler96** [comment]
Thanks JakobBozic!
But i have a question that how you control the fully labeled samples number in the code ? I did not find this in dataset.py and end2end.py files, could you give me some guidance how to control the N above the all training positive samples?

**Comment by smiler96** [comment]
> Hi,
> the number in the name of the split for KSDD2 represents the number of fully labeled samples (N in the paper).
> The number of positive training samples for KSDD2 is always 246 for all experiments.
> I have updated all README.md files in the splits directory with better explanations of the numbers in the names.

Thanks a lot, jakobBozic!
I got it but i am confused that how you split the data? randomly chose?

**Comment by JakobBozic** [comment]
Hi, 
the data was split randomly.
