### ISSUE TITLE
It seems no evalutation about segmentation

### ISSUE THREAD

**Issue by HustHB** [vicoslab/mixed-segdec-net-comind2021#5]
First, thanks for your public nice code!

I just wonder whether the AP metric in paper is about classification rather than semantic segmentation.
And in your "end2end.py " L246, it seems only evaluate for "predictions" which is result of classification.

By the way, I think "**weakly supervision**" is not precise in your mix supervision setting, because if your final evaluation is only about classification, class-level, pixel-level labels will all be full-supervised label for classification.

**Comment by JakobBozic** [comment]
Hi, 
all of the metrics that we report in the paper are about classification, as it is the most relevant metric in industrial defect detection.

**Comment by smiler96** [comment]
> Hi,
> all of the metrics that we report in the paper are about classification, as it is the most relevant metric in industrial defect detection.

The AP is adopted the metric for evaluation, would you provide the AUC values both in this repo?

**Comment by HustHB** [comment]
> Hi,
> all of the metrics that we report in the paper are about classification, as it is the most relevant metric in industrial defect detection.

Thanks for your rapid reply! ^_^
