### ISSUE TITLE
Question about init_extra()

### ISSUE THREAD

**Issue by Youskrpig** [vicoslab/mixed-segdec-net-comind2021#7]
In dataset.py, line 24 
self.pos_imgs_permutation = np.random.permutation(self.num_neg) 
Should  self.num_neg be self.num_pos?

**Comment by JakobBozic** [comment]
Hi,
self.pos_imgs_permutations (also self.pos_retrieval_freq) is actually never used, we forgot to remove it when cleaning the code before the release. I have removed it now, thank you for your notice.
