### ISSUE TITLE
Question about Total_correct

### ISSUE THREAD

**Issue by Youskrpig** [vicoslab/mixed-segdec-net-comind2021#8]
end2end.py, line113:
total_correct += (decision > 0.5).item() == is_pos_.item()
decision is the output of model(fc layer)，it‘s not a probability,  Is function sigmoid() missed?

**Comment by JakobBozic** [comment]
Hi, 
you are correct, we missed a sigmoid calculation there. I have updated the threshold to 0.0 which corresponds to the sigmoid value of 0.5.
