### ISSUE TITLE
How to generate the split file(.pyb) for my own data?

### ISSUE THREAD

**Issue by Youskrpig** [vicoslab/mixed-segdec-net-comind2021#9]
Could you please share the dataset split code?

**Comment by JakobBozic** [comment]
Hi, 
to use your own data, you don't necessarily need to use splits. All that it matters is, that you provide the data batches in the correct format, you can check it either in dataset.py (line 62) or in various places in end2end.py. 
You can extend the data.Dataset class and read the positive and negative samples to self.pos/neg_samples, which will by default also enable 1-1 sampling of positive and negative samples. You can also write your own implementation. You can find a more detailed description in README.md in the datasets folder.
